### ISSUE TITLE
Players can take items away while the item exchange starts

### ISSUE THREAD

**Issue by Lajtmen** [fewizz/Trade#2]
Players can take item away while the item exchange starts. So for example the trade is counting down 3..2..1.. and player can take item away in last second so if second player wont do that too he will lose his item.

**Comment by fewizz** [comment]
Build with fix uploaded to curseforge for mc 1.12.

**Comment by Lajtmen** [comment]
Can you update it to 1.10.2 please. I will really appreciate that. :) 👍

**Comment by fewizz** [comment]
https://minecraft.curseforge.com/projects/trade/files/2521957

**Comment by Lajtmen** [comment]
u are the best :D XD

**Comment by fewizz** [comment]
👌
