### ISSUE TITLE
1.12.2 - Trade problem, maybe SpongeForge related?

### ISSUE THREAD

**Issue by Krosta8** [fewizz/Trade#3]
Hello,
I found a problem with latest version of Trade (1.0.3) for Minecraft 1.12.2.
When player is in trade with another player and player is holding item in hand, one of them ESC the trade, item from his hand "disappear", then open inventory, close inventory and item from hand drop on the ground.

I don't know, if it is Sponge related or just problem in the mod.

Let me know, if you need more information about this problem, I tried to explain it how much how I can :D 
Also good to mention, using Forge 2611

**Comment by fewizz** [comment]
will check soon(tm)

**Comment by fewizz** [comment]
Can't reproduce on clear forge\

**Comment by Krosta8** [comment]
Oh, okay. Thank you anyway.
I think, that it is not possible to make this mod compatible with Sponge platform, right?
Because my another idea was about hook to economy-API on Sponge to be able to trade not only for items, but for money too.
