### ISSUE TITLE
1.12.2 - SHIFT + LM on cobblestone when trade

### ISSUE THREAD

**Issue by ghost** [fewizz/Trade#4]
When I press V, request sent, after that i can see trade window and if I hold SHIFT + Mouse_Left click on block of cobblestone in my inventory everything crashes.

**Comment by fewizz** [comment]
Можешь проверить?/
[mod_unpackme.zip](https://github.com/fewizz/Trade/files/1756251/mod.zip)

**Comment by ghost** [comment]
It works! thanks! Please update it on curse. Also i recommend to make releases on github. Your mod is awesome.
