### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [fewizz/Trade#5]
Is the license same as the one on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/trade) (MIT)? I'd like to contribute some of my changes [but the lack of license in this repo makes it impossible](https://help.github.com/en/articles/licensing-a-repository#choosing-the-right-license).

**Comment by fewizz** [comment]
I have no way to make pr atm. Yep, thats mip
